name: alphabet_scroll_view
description:
  A Scrollable ListView Widget with the dynamic vertical Alphabet List which
  you can drag and tap to scroll to the first item starting with that letter.
version: 0.3.2
homepage: https://github.com/maheshmnj/alphabet_scroll_view
repository: https://github.com/maheshmnj/alphabet_scroll_view
issue_tracker: https://github.com/maheshmnj/alphabet_scroll_view

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: 1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

